### ISSUE TITLE
Process to Build Xenial Stemcells

### ISSUE THREAD

**Issue by mheadd** [cloud-gov/cg-deploy-bosh#440]
Prior to migrating to Bionic stemcells, there may be a need to build Xenial stemcells and continue using them as we conduct testing to support our transition to Bionic. (Note - this assumes we won't have access to already built stemcells as a part of our support package.)

- [ ] Set up pipeline to build Xenial stemcells
- [ ] Create test suite for built stemcells

There will be ongoing work required for this task as new stemcells will be released periodically, so the build pipeline will need to be kicked off, tests run, and new stemcells deployed.

Related to this [issue](https://github.com/cloud-gov/product/issues/1548).

**Comment by mheadd** [comment]
Potentially related to this work: https://gsa-tts.slack.com/archives/C0A1Z7L2U/p1620776090006900

**Comment by bengerman13** [comment]
No longer relevant
